-- 21.12.15
-- SEQUENCE : 일렬번호 생성하기

SELECT * FROM BOOK;
-- 새로운 책을 BOOK TABLE에 등록할 때 마다 BOOKID 번호를 INSERT 명렁어에 직접 넣을 때
-- 순차적으로넣지 못할 경우 발생 (현재 최종 등록된 BOOKID는 2000인 경우, 
-- 다음 BOOKID는 2001로 등록해야 하는데 2002 등 다른 숫자로 등록할 수 있는 경우 발생

-- (예) 마당에서 입력시 
-- INSERT INTO BOOK
-- VALUES (11, 'TEST', 'PB1', 30000);
-- 쓰는 경우가 꼭 생긴다. 숙지해야함.

-- SEQUENCE 생성하기
CREATE SEQUENCE DEPT_DEPTNO_SEQ
INCREMENT BY 10
START WITH 10;


-- 생성된 SEQUENCE 객체 DEPT_DEPT_SEQ 사용하기
-- NEXTVAL(NEXT VALUE), CURRVAL (CURRENT VALUE) 명령어 사용

SELECT DEPT_DEPTNO_SEQ.NEXTVAL FROM DUAL;

SELECT DEPT_DEPTNO_SEQ.CURRVAL FROM DUAL;

-- 실제 사용 예
CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 100000; -- 추가 CYCLE 회전 10만까지 가면 다시 1로 된다.

DROP TABLE EMP01;

CREATE TABLE EMP01 (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    HIREDATE DATE
);

SELECT * FROM EMP01;

INSERT INTO EMP01
VALUES(EMP_SEQ.NEXTVAL, 'JULIA', SYSDATE);

INSERT INTO EMP01
VALUES (EMP_SEQ.NEXTVAL, 'MARY', SYSDATE);

INSERT INTO EMP01
VALUES (EMP_SEQ.NEXTVAL, 'ROBERT', SYSDATE);

SELECT * FROM EMP01;

-- SEQUENCE 삭제하기
DROP SEQUENCE DEPT_DEPTNO_SEQ;