SET SERVEROUTPUT ON
DECLARE
    TYPE EMP_RECORD_TYPE IS RECORD(
        V_EMPNO  EMP.EMPNO%TYPE,
        V_ENAME  EMP.ENAME%TYPE,
        V_JOB    EMP.JOB%TYPE,
        V_DEPTNO EMP.DEPTNO%TYPE
    );
    EMP_RECORD EMP_RECORD_TYPE;
BEGIN
    SELECT EMPNO, ENAME, JOB, DEPTNO INTO EMP_RECORD
        FROM EMP
        WHERE UPPER(ENAME)='SCOTT';
    DBMS_OUTPUT.PUT_LINE('사원번호 : ' || TO_CHAR(EMP_RECORD.V_EMPNO) );
    DBMS_OUTPUT.PUT_LINE('이   름 : ' || EMP_RECORD.V_ENAME );
    DBMS_OUTPUT.PUT_LINE('담당업무 : ' || EMP_RECORD.V_JOB );
    DBMS_OUTPUT.PUT_LINE('부서번호 : ' || EMP_RECORD.V_DEPTNO );
END;
/